In [75]:
import sys
import os
import io
import glob
import json
import html 
#from PyPDF2 import PdfReader
#from markdownify import markdownify as md
from azure.ai.formrecognizer import DocumentAnalysisClient

#from azure.ai.documentintelligence import DocumentIntelligenceClient
#from azure.ai.documentintelligence.models import AnalyzeDocumentRequest, ContentFormat, AnalyzeResult

from azure.core.credentials import AzureKeyCredential
#from azure.identity import AzureDeveloperCliCredential
from azure.storage.blob import BlobServiceClient
import requests
from dotenv import load_dotenv
load_dotenv("./ez_env.env")

True

In [3]:
from pdf_smart_splitter.main import PDFSmartSplitter

filename ="./in/P-1223-23 - Final.pdf" # "./in/2021-111P.pdf"
pdfSmartSplitter = PDFSmartSplitter(env_filename="./ez_env.env",pdf_filename=filename,verbose=1)

res = pdfSmartSplitter.run()#(save_path = "./out")

pages:196
tables:170
sections:286
paragraphs:5759

c:\Users\ezzatdemnati\OneDrive - Microsoft\Documents\src\pdfextractor\pdf_smart_splitter\main.py:139: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  parent_id=int(self.df_doc_parent_sections[self.df_doc_parent_sections.section==str(id)].parent)
c:\Users\ezzatdemnati\OneDrive - Microsoft\Documents\src\pdfextractor\pdf_smart_splitter\main.py:151: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.df_doc_parent_sections["level"] = self.df_doc_parent_sections["level"].fillna(0).astype(str)

In [4]:
res_chunks = pdfSmartSplitter.chunk_documnent()

res_chunks

chunk_is_null count:0
chunk_is_true count:236
chunk_is_false count:50

c:\Users\ezzatdemnati\OneDrive - Microsoft\Documents\src\pdfextractor\pdf_smart_splitter\main.py:355: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['["\\n27"]', '["\\n150\\n<table><tr><td>System Owner</td><td>Halton, The Regional Municipality of</td></tr><tr><td>ECA Number</td><td>004-W601</td></tr><tr><td>System Name</td><td>Halton Region Wastewater Collection System</td></tr><tr><td>ECA Issue Date</td><td>May 9, 2023</td></tr></table>\\n\\nMay 9, 2023\\n1.0 General\\n<table><tr><th>Table C1: Schedule C Notices</th></tr><tr><th>Column 1 Issue #</th><th>Column 2 Issue Date</th><th>Column 3 Description</th><th>Column 4 Status</th><th>Column 5 DN#</th></tr><tr><td>N/A</td><td>N/A</td><td>N/A</td><td>N/A</td><td>N/A</td></tr></table>"]', '["\\n8.1.2 The terms and conditions of the revoked approval that were applicable as of the date this approval was issued, provided that the Alteration is commenced within five (5) years of the date that the revoked approval was issued.\\n9.0 Transition\\n9.1 An Alteration of the Authorized System is exempt from the requirements in clause (c) of condition 4.1.1 and clause (c) of condition 5.2.1 where:\\n9.1.1 Effort to undertake the Alteration, such as tendering or commencement of construction of the Sewage Works associated with the Alteration, begins on or before May 22, 2023.\\n9.1.2 The design of the Alteration conforms to the Design Guidelines for Sewage Works;\\nMay 9, 2023\\ncompleted for the Alteration and changes to the design result in significant cost increase or significant project delays; and"]', '["\\n195\\n<table><tr><td>System Owner</td><td>Halton, The Regional Municipality of</td></tr><tr><td>ECA Number</td><td>004-W601</td></tr><tr><td>System Name</td><td>Halton Region Wastewater Collection System</td></tr><tr><td>ECA Issue Date</td><td>May 9, 2023</td></tr></table>\\n\\nMay 9, 2023\\n\\n1.0 Residue Management System"]']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  self.df_doc_sections_merge.loc[(self.df_doc_sections_merge.level==l)

,section,parent,level,elements,offset,length,section_max,sections,paragraphs,tables,...,section_content,section_all_content,content_len,all_content_len,is_chunk,chunk,chunks,chunks_count,chunks_max_len,chunks_len
0,0,NaN,0,"[/sections/1, /sections/2, /sections/66, /sect...",0,460494,460494,"[1, 2, 66, 67, 76, 230, 254, 256, 262, 265, 26...",[],[],...,,,0,0,False,None,NaN,0,0,0
1,1,0,1,[/figures/0],0,34,34,[],[],[],...,,,0,0,False,None,NaN,0,0,0
2,2,0,1,"[/paragraphs/1, /paragraphs/2, /paragraphs/3, ...",37,71561,71598,"[3, 5, 27, 32, 46, 59]","[1, 2, 3, 4, 5]",[],...,\nHalton REGION\nTHE REGIONAL MUNICIPALITY OF ...,\nHalton REGION\nTHE REGIONAL MUNICIPALITY OF ...,246,61415,True,None,"[""\nHalton REGION\nTHE REGIONAL MUNICIPALITY O...",1,246,[246]
3,3,2,2,"[/paragraphs/7, /paragraphs/8, /paragraphs/9, ...",378,1298,1676,[4],"[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ...",[],...,\nTABLE OF CONTENTS\nSECTION 1: SUBMISSION INS...,\nTABLE OF CONTENTS\nSECTION 1: SUBMISSION INS...,609,1240,True,None,"[""\nTABLE OF CONTENTS\nSECTION 1: SUBMISSION I...",1,1240,[1240]
4,4,3,3,"[/paragraphs/29, /paragraphs/30, /paragraphs/3...",1023,653,1676,[],"[29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4...",[],...,\n1.20 Freedom of Information\nSECTION 2: TERM...,\n1.20 Freedom of Information\nSECTION 2: TERM...,630,630,False,None,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,281,268,2,"[/paragraphs/5673, /paragraphs/5674, /paragrap...",454556,5342,459898,[282],"[5673, 5674, 5675, 5676, 5677, 5678, 5679, 568...",[],...,\niv Identification of any near and/or long-te...,\niv Identification of any near and/or long-te...,3747,4148,True,None,"["" iv Identification of any near and/or long-...",2,2603,"[2603, 1146]"
282,282,281,3,"[/paragraphs/5728, /paragraphs/5729, /paragrap...",459211,687,459898,[],"[5728, 5729, 5730, 5738, 5739]",[],...,\n8.2.4 The Owner shall ensure that an updated...,\n8.2.4 The Owner shall ensure that an updated...,400,400,True,None,"[""\n8.2.4 The Owner shall ensure that an updat...",1,400,[400]
283,283,0,1,"[/paragraphs/5744, /tables/169, /sections/284]",460114,380,460494,[284],[5744],[169],...,\n195\n<table><tr><td>System Owner</td><td>Hal...,\n195\n<table><tr><td>System Owner</td><td>Hal...,272,316,True,None,"[""\n195\n<table><tr><td>System Owner</td><td>H...",1,316,[316]
284,284,283,2,"[/paragraphs/5753, /sections/285]",460436,58,460494,[285],[5753],[],...,"\nMay 9, 2023","\nMay 9, 2023\n\n1.0 Residue Management System",12,43,False,None,NaN,0,0,0
285,285,284,3,[/paragraphs/5754],460471,23,460494,[],[5754],[],...,\n1.0 Residue Management System,\n1.0 Residue Management System,30,30,True,None,"[""\n1.0 Residue Management System""]",1,30,[30]

In [146]:
max_chunk_len = 2500
chunk_overlap = 500
res["is_chunk"] = None
res["chunk"] = None

def turnoff_sub_sections_chunking(df):
    for i, row in df.iterrows():
        for s in row.sections:
            res.loc[res.section==s,["is_chunk"]] =False

def resolve_parent_section_chunking(df,l):
    for p in df.parent.drop_duplicates(): 
        if len(res[(res.parent==p) & (res.is_chunk.isnull())])==0:
            res.loc[(res.section==p),["is_chunk"]] =False

def split_content_to_chunks(content,chunk_max_len,chunk_overlap):
    import json
    
    content_list = content.split("\n")
    temp = ""
    chunks=[]
    for c in content_list:
        temp=temp +" " + c
        if len(temp)>chunk_max_len:
            chunks.append(temp)
            temp=" "
    if len(temp)>0:
            chunks.append(temp)
            
    """
    chunk_count = len(content)//chunk_max_len
    for c in range(chunk_count+1):
        if c>0:
            min = c*chunk_max_len-chunk_overlap
        else:
            min=c*chunk_max_len
        
        if c<(chunk_count+1):
            max = (c+1)*chunk_max_len+chunk_overlap
        else:
            max=(c+1)*chunk_max_len

        chunks.append(content[min:max])
    """
    return json.dumps(chunks)

res.loc[(res.all_content_len<1),"is_chunk"] = False

        
for l in res.level.drop_duplicates(): 
    # STEP 1: if level l section with all_content_len<max_chunk_len then tag the whole content as one chunk
    res.loc[(res.level==l) 
            & (res.all_content_len<max_chunk_len) 
            & (res.is_chunk.isnull()),["chunks"]] = res[(res.level==l) 
                                                         & (res.all_content_len<max_chunk_len) 
                                                         & (res.is_chunk.isnull())].section_all_content.apply(lambda x:json.dumps([x]))
    res.loc[(res.level==l) 
            & (res.all_content_len<max_chunk_len) 
            & (res.is_chunk.isnull()),["is_chunk"]] =True
            
    # turnoff sub-sections from chunking for sections with all_content_len<max_chunk_len
    turnoff_sub_sections_chunking(res[(res.level==l) & (res.all_content_len<max_chunk_len) & (res.is_chunk==True)])

    #  STEP 2: Chunk remaining sections
    # 2.1: Add section level content as chunk if it is less than max_chunk_len
    res.loc[(res.level==l) 
            & (res.content_len<max_chunk_len)
             & (res.is_chunk.isnull()),["chunks"]] = res[(res.level==l) 
                                                          & (res.content_len<max_chunk_len)
                                                          & (res.is_chunk.isnull())].section_content.apply(lambda x:json.dumps([x]))
    
    # 2.2: If content_len is less than max_chunk_len then tag the section content as one chunk
    res.loc[(res.level==l) 
            & (res.content_len<max_chunk_len) 
            & (res.is_chunk.isnull()),["is_chunk"]] =True
    
    # 2.3: If not, split the content into chunks
    res.loc[(res.level==l) 
            & (res.content_len>max_chunk_len) 
            & (res.is_chunk.isnull()),["chunks"]] = res[(res.level==l) 
                                                            & (res.content_len>max_chunk_len) 
                                                            & (res.is_chunk.isnull())].section_content.apply(lambda x:split_content_to_chunks(x,max_chunk_len,chunk_overlap))
    # 2.4: Split chunk content if content_len>max_chunk_len
    
    # 2.5: Tag splitted chunks are completed (is_chunk=True)
    res.loc[(res.level==l) 
            & (res.content_len>max_chunk_len) 
            & (res.is_chunk.isnull()),["is_chunk"]] =True


    # Turnoff parent section from chunking if all sub-sections are chunked
    #resolve_parent_section_chunking(res[(res.level==l)],l)

# Update all sections with all_content_len>max_chunk_len and is_chunkis None to is_chunk=False
#res.loc[(res.all_content_len>max_chunk_len) & (res.is_chunk.isnull()),["is_chunk"]] =False

print(len(res[(res.is_chunk.isnull())]))
print(len(res[(res.is_chunk==True)]))
print(len(res[(res.is_chunk==False)]))

def count_chunks(chunks):
    try:
        if chunks is None:
            return 0
        return len(json.loads(chunks))
    except:
        return 0
def len_max_chunks(chunks):
    try:
        if chunks is None:
            return 0
        max=0
        for c in json.loads(chunks):
            if len(c)>max:
                max=len(c)
        return max
    except:
        return 0
    
def len_chunks(chunks):
    try:
        if chunks is None:
            return 0
        
        return [len(c)for c in json.loads(chunks)]
    except:
        return 0
    
res["chunks_count"] = res.chunks.apply(lambda x:count_chunks(x))
res["chunks_max_len"] = res.chunks.apply(lambda x:len_max_chunks(x))
res["chunks_len"] = res.chunks.apply(lambda x:len_chunks(x))

0
134
43

In [147]:
for l in json.loads(res.loc[res.section==55].chunks.values[0]):
    print(l)
    print("*"*100)

  · Preliminary design of assignments that are identified as Schedule B or C are NOT part of the scope of this RFP. 4.1. Element 6 - TM#6 - Preparation for Preliminary Design 4.1.1. It is understood that some work need to be done prior to preparation of Preliminary Design Reports (PDR). The preparation work will be performed in this Element of the project and the results will be reported in a TM. Critical tasks of this Element are described here. The descriptions are general and non-specific. The consultant is expected to develop a workplan specific to the needs of the project as part of workplan included in the Block Study report and have it approved by the Agency. Document 2021-111P Regional Municipality of Peel-Procurement Division BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1 WITHIN THE CITY OF MISSISSAUGA Terms of Reference failure to review and verify documents or drawings will be at the consultant's own cost. 4.1.3. Visit the site as required to determine existing condition, locations, services, features, routes, access, interference, etc., related to the proposed design. 4.1.4. Engineering survey: The consultant will be required to complete an engineering survey for the preparation of engineering drawings. The engineering survey shall be a full topographical survey with 5 millimetre accuracy, from property line to property line for the entire length of the Assignment location. The engineering survey shall follow good survey practice, including but not limited to rationing elevation at least every 10 meters if a more stringent requirement (i.e. alignment changes, and low points) is not identified. It must confirm location and elevation of all curb, curb and gutter, sidewalk, driveways, bike paths, ditches, pavement marking, utility surface features, all shrubs, planting beds, trees specifying species and trunk diameter, drip lines, fences, parking pavement marking, berms, bus shelters, benches planters, street furniture, top of lid elevation for all maintenance holes & catch basins & vale chambers & valve boxes, fire hydrants, raining walls & fences, surface material (e.g. asphalt, concrete, pavers, sod, etc.), and any other feature that may affect constructability or have significant impact on construction or restoration cost. It must be tied to the Agency's geodetic datum, and horizontal and vertical control points. It shall conform to the Agency's standard and shall indicate the appropriate CAD layers, symbols, and standard nomenclature that are to be used for all drawings. Upon completion of the engineering survey and processing, the consultant shall complete quality control review of the product. All base plan and design drawings must meet the requirements of the Agency's CADD Specification Manual.
****************************************************************************************************
  Document 2021-111P Regional Municipality of Peel-Procurement Division BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1 WITHIN THE CITY OF MISSISSAUGA Terms of Reference The Consultant shall be responsible for verifying this information in the field. Any discrepancies or conflicts are to be reported to the Agency. This include: 1 Set horizontal control line in accordance with the City's requirements with ties to existing property bars and topographic information. .2 Set elevation control bench marks clear of the expected construction area to allow referencing of further detailed elevation information, as well as the development and control of elevations of the works to be constructed under this project. .3 Provide any other necessary survey work required to complete the design of the project. .4 Provide all survey notes for layout purposes. 4.1.6. Photo Album of Existing Condition: Undertake a visual survey of the existing building envelope within the project areas. With digital photographs, the Consultant shall document the exiting field conditions, potential costs related to restoration (including landscaping, driveways, fences), assets that are not within shapefiles (such as manholes, catch basins, etc.), process tanks, roofs, and surfaces finish conditions and reverse slope driveways. The photo album is a pdf file with all the photos labelled with location (including civic address) that it was taken from, what is shown in the photo and date. The PDFs must be searchable. A digital georeferenced copy of every photo to be delivered to the Agency as well. 4.1.7. Topographic survey: A topographic survey of the project is required. 4.1.8. Easement requirements: The consultant shall confirm the need for new or additional easement. They shall confirm this by consulting the Agencies representative department, records and drawings, as well as confirmation in the field. Document 2021-111P Regional Municipality of Peel-Procurement Division BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1 WITHIN THE CITY OF MISSISSAUGA Terms of Reference location (including tree Tag# and street address), species (common and botanical names), size (diameter at breast height, drip line radius and tree protection zone), health (disease and infestations), condition (crown vigor) and structural integrity. Any tree of significance (based on size, species, or condition) or species of concern will be noted in the tables and graphical representations for preservation priority and tree protection measures. The work must be performed in close coordination with the Agency's respective departments as well as lower tier municipalities, and conservation authorities.
****************************************************************************************************
  4.1.10. Cultural heritage resource assessments within heritage properties, archaeological sites, and lands of archaeological potential, if required. The assessment must be conducted by a member of the Canadian Association of Professional Heritage Consultants. 4.1.11. If installation of backwater preventor valve was to be considered, the consultant shall perform site visit and interview with owners of respective properties to reaffirm the suitability of the proposal for each particular property. The consultant is expected to review the available background documentation related to these properties, such as Hansen reports, CCTV data, etc. to be aware of potential flooding causes prior to visiting these properties. The consultant is expected to create and complete a resident interview form to record the relevant information for each property. The consultant shall provide the Agency a report for each property including all the information mentioned above in a organized format.
****************************************************************************************************

In [442]:
formrecognizer_creds = AzureKeyCredential(os.getenv("AZURE_FORM_RECOGNIZER_KEY"))
                        
form_recognizer_client = DocumentAnalysisClient(
    endpoint=os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT"),
    credential=formrecognizer_creds,
    headers={"x-ms-useragent": "azure-search-chat-demo/1.0.0"},
)

In [443]:


# Process file from local folder
filename = "./in/2021-111P.pdf"
with open(filename, "rb") as f:
    poller = form_recognizer_client.begin_analyze_document("prebuilt-layout", document=f)
form_recognizer_results = poller.result()

# Process file from Blob storage URL
#poller = form_recognizer_client.begin_analyze_document_from_url("prebuilt-layout", document_url=filename)

In [7]:
print(f"pages:{len(form_recognizer_results.pages)}")
print(f"tables:{len(form_recognizer_results.tables)}")

pages:87
tables:45

In [76]:
#NEW API
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest, ContentFormat, AnalyzeResult


document_intelligence_creds = AzureKeyCredential(os.getenv("AZURE_FORM_RECOGNIZER_KEY"))

# Document Intelligence Output to markdown format
document_intelligence_client = DocumentIntelligenceClient(endpoint=os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT"), 
                                                            credential=document_intelligence_creds)

#poller = document_intelligence_client.begin_analyze_document(
#    "prebuilt-layout",
#    AnalyzeDocumentRequest(url_source=filename),
#    output_content_format=ContentFormat.MARKDOWN,
#)
filename = "./in/2021-111P.pdf"
with open(filename, "rb") as f:
        poller = document_intelligence_client.begin_analyze_document(
        "prebuilt-layout",
        #AnalyzeDocumentRequest(url_source=filename),
        AnalyzeDocumentRequest(bytes_source=f.read()),        
        output_content_format=ContentFormat.MARKDOWN,
    )

result_mkd: AnalyzeResult = poller.result()

In [77]:
print(f"pages:{len(result_mkd.pages)}")
print(f"tables:{len(result_mkd.tables)}")
print(f"sections:{len(result_mkd.sections)}")
print(f"paragraphs:{len(result_mkd.paragraphs)}")

pages:87
tables:13
sections:177
paragraphs:1474

In [85]:
parent_level

{0: 0,
 2: 1,
 9: 2,
 11: 2,
 14: 2,
 19: 1,
 22: 2,
 24: 2,
 26: 2,
 27: 3,
 33: 1,
 34: 2,
 35: 3,
 37: 2,
 38: 3,
 42: 2,
 43: 3,
 45: 4,
 47: 3,
 48: 4,
 52: 3,
 54: 2,
 56: 3,
 59: 2,
 61: 3,
 65: 3,
 67: 4,
 70: 3,
 71: 4,
 74: 3,
 75: 4,
 78: 3,
 79: 4,
 83: 3,
 86: 1,
 88: 2,
 90: 3,
 91: 4,
 94: 5,
 97: 1,
 98: 2,
 102: 2,
 106: 2,
 110: 2,
 112: 2,
 117: 2,
 120: 3,
 124: 2,
 126: 2,
 127: 3,
 129: 2,
 133: 2,
 136: 2,
 138: 2,
 140: 3,
 145: 2,
 148: 3,
 149: 4,
 151: 2,
 159: 2,
 161: 1,
 165: 1,
 171: 2,
 175: 2}

In [100]:
import pandas as pd
df_doc_parent_sections = pd.DataFrame(columns=["section","parent","level"])
parent_level={0:0}
level = 0
stop=0
for id,s in enumerate(result_mkd.sections):
    s_dict=s.as_dict()
    levelup=0
   
    
    for e in s_dict["elements"]:
        if "sections" in e:            
            try:
                level = parent_level[id]+1                
            except:
                parent_id=int(df_doc_parent_sections[df_doc_parent_sections.section==str(id)].parent)
                level=parent_level[parent_id]+1
                parent_level[id]=level
                #parent_level[e.split("/")[-1]]=level+1
                level = parent_level[id]+1 
                pass

            df_doc_parent_sections = pd.concat([df_doc_parent_sections, pd.DataFrame([{"section":e.split("/")[-1],"parent":id,"level":level}])], ignore_index=True)


        
df_doc_parent_sections.head(20)#[df_doc_parent_sections.parent==2]

C:\Users\ezzatdemnati\AppData\Local\Temp\ipykernel_30960\1230027336.py:16: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  parent_id=int(df_doc_parent_sections[df_doc_parent_sections.section==str(id)].parent)

   section parent level
0        1      0     1
1        2      0     1
2       19      0     1
3       33      0     1
4       86      0     1
5       96      0     1
6       97      0     1
7      161      0     1
8      164      0     1
9      165      0     1
10       3      2     2
11       4      2     2
12       5      2     2
13       6      2     2
14       7      2     2
15       8      2     2
16       9      2     2
17      11      2     2
18      13      2     2
19      14      2     2

In [102]:
doc_sections=[]
temp = None

for id,s in enumerate(result_mkd.sections):
    s_dict=s.as_dict()
    if temp and s_dict.get("spans")[0].get("offset")<temp.get("section_max"):
        level+=1
    else:
        level=0
       
    temp = {"section":id,
            "elements": s_dict.get("elements"), 
            "offset": s_dict.get("spans")[0].get("offset"), 
            "length": s_dict.get("spans")[0].get("length"),
            "section_max": s_dict.get("spans")[0].get("length") +s_dict.get("spans")[0].get("offset")
            } 
        
    doc_sections.append(temp)

import pandas as pd 
import numpy as np
df_doc_sections = pd.DataFrame(doc_sections)
df_doc_sections["section"] = df_doc_sections["section"].astype(int)
df_doc_parent_sections["section"] = df_doc_parent_sections["section"].astype(int)
df_doc_parent_sections["parent"] = df_doc_parent_sections["parent"].astype(str)
df_doc_parent_sections["level"] = df_doc_parent_sections["level"].fillna(0).astype(str)

df_doc_sections_merge = pd.merge(df_doc_parent_sections,df_doc_sections,left_on="section",right_on="section",how="outer",indicator=True)
df_doc_sections_merge["level"] = df_doc_sections_merge["level"].fillna(0)
df_doc_sections_merge.sort_values(["parent","section"],ascending=True)[df_doc_sections_merge.level.isin(["0","1","2"])].head(50)


# elements columns ins a list of paragraphs and section elemetsn. split elements into separate columns for list of paragraphs and list of sections and list of others
df_doc_sections_merge["sections"] = df_doc_sections_merge["elements"].apply(lambda x: [int(p.split("/")[-1]) for p in x if "sections" in p])
df_doc_sections_merge["paragraphs"] = df_doc_sections_merge["elements"].apply(lambda x: [int(p.split("/")[-1]) for p in x if "paragraphs" in p])
df_doc_sections_merge["tables"] = df_doc_sections_merge["elements"].apply(lambda x: [int(p.split("/")[-1]) for p in x if "tables" in p])
df_doc_sections_merge["figures"] = df_doc_sections_merge["elements"].apply(lambda x: [int(p.split("/")[-1]) for p in x if "figures" in p])
df_doc_sections_merge["others"] = df_doc_sections_merge["elements"].apply(lambda x: [p for p in x if "sections" not in p and "paragraphs" not in p and "tables" not in p and "figures" not in p])

df_doc_sections_merge.head(20)


#.to_csv("./sections.csv",index=False)

C:\Users\ezzatdemnati\AppData\Local\Temp\ipykernel_30960\2155227315.py:30: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_doc_sections_merge.sort_values(["parent","section"],ascending=True)[df_doc_sections_merge.level.isin(["0","1","2"])].head(50)

,section,parent,level,elements,offset,length,section_max,_merge,sections,paragraphs,tables,figures,others
0,0,NaN,0,"[/sections/1, /sections/2, /sections/19, /sect...",0,216691,216691,right_only,"[1, 2, 19, 33, 86, 96, 97, 161, 164, 165]",[],[],[],[]
1,1,0,1,[/figures/0],0,52,52,both,[],[],[],[0],[]
2,2,0,1,"[/paragraphs/1, /paragraphs/2, /paragraphs/3, ...",55,29900,29955,both,"[3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 16, 17, 18]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[],[],[]
3,3,2,2,"[/paragraphs/37, /paragraphs/38, /paragraphs/3...",2666,5633,8299,both,[],"[37, 38, 39, 40, 41, 42, 46, 47, 48, 49, 50, 5...",[],[],[]
4,4,2,2,"[/paragraphs/68, /paragraphs/69, /paragraphs/7...",8302,3457,11759,both,[],"[68, 69, 70, 71, 72, 76, 77, 78, 79, 80, 81, 8...",[],[],[]
5,5,2,2,"[/paragraphs/84, /paragraphs/85, /paragraphs/8...",11762,1725,13487,both,[],"[84, 85, 86, 90, 91]",[],[],[]
6,6,2,2,"[/paragraphs/92, /paragraphs/93]",13490,204,13694,both,[],"[92, 93]",[],[],[]
7,7,2,2,"[/paragraphs/94, /paragraphs/95, /paragraphs/96]",13697,2110,15807,both,[],"[94, 95, 96]",[],[],[]
8,8,2,2,"[/paragraphs/97, /paragraphs/98]",15810,323,16133,both,[],"[97, 98]",[],[],[]
9,9,2,2,"[/paragraphs/99, /paragraphs/100, /sections/10]",16136,2004,18140,both,[10],"[99, 100]",[],[],[]
10,10,9,3,"[/paragraphs/104, /paragraphs/105, /paragraphs...",16575,1565,18140,both,[],"[104, 105, 106, 107, 108, 109, 110, 111, 112]",[],[],[]
11,11,2,2,"[/paragraphs/113, /paragraphs/114, /paragraphs...",18143,1762,19905,both,[12],"[113, 114, 115, 116]",[],[],[]
12,12,11,3,"[/paragraphs/120, /paragraphs/121, /paragraphs...",19219,686,19905,both,[],"[120, 121, 122, 123]",[],[],[]
13,13,2,2,"[/paragraphs/124, /paragraphs/125, /paragraphs...",19908,2039,21947,both,[],"[124, 125, 126, 164, 165]",[0],[],[]
14,14,2,2,"[/paragraphs/166, /paragraphs/167, /paragraphs...",21950,4813,26763,both,[15],"[166, 167, 168, 169, 170, 171, 172, 175]",[],[],[]
15,15,14,3,"[/paragraphs/176, /paragraphs/177, /paragraphs...",24981,1782,26763,both,[],"[176, 177, 178, 182, 183, 187]","[1, 2]",[],[]
16,16,2,2,"[/paragraphs/188, /paragraphs/189]",26766,313,27079,both,[],"[188, 189]",[],[],[]
17,17,2,2,"[/paragraphs/190, /paragraphs/191, /paragraphs...",27082,2009,29091,both,[],"[190, 191, 195, 196, 197, 198, 199, 200, 201, ...",[],[],[]
18,18,2,2,"[/paragraphs/204, /paragraphs/205, /paragraphs...",29094,861,29955,both,[],"[204, 205, 206]",[],[],[]
19,19,0,1,"[/paragraphs/210, /paragraphs/211, /sections/2...",30205,17840,48045,both,"[20, 21, 22, 24, 26, 29, 30, 31, 32]","[210, 211]",[],[],[]

In [552]:
# Prepare doc paragraphs
doc_paragraphs=[]

for i,p in enumerate(result_mkd.paragraphs):
    p_dict=p.as_dict()
    temp = {"id":i+1,
            "section":None,
            "content": p_dict.get("content"), 
            "role": p_dict.get("role"), 
            "pageNumber": p_dict.get("boundingRegions")[0].get("pageNumber"), 
            "offset": p_dict.get("spans")[0].get("offset"), 
            "length": p_dict.get("spans")[0].get("length")
            } 
    #if p.role  in ('sectionHeading', 'title'):

    
    doc_paragraphs.append(temp)

import pandas as pd 
df_doc_paragraphs = pd.DataFrame(doc_paragraphs)

# Merge sections and paragraphs
df_doc_paragraphs.set_index("id",inplace=True)
for i,s in df_doc_sections_merge.iterrows():
    for p in s.elements:
        if "paragraphs" in p:
            try:
                df_doc_paragraphs.loc[int(p.split("/")[-1]),["section"]] = s.section
            except:
                pass

In [553]:
# Prepare doc tables
doc_tables=[]

def table_to_html(table):
    table_html = "<table>"
    rows = [
        sorted([cell for cell in table.cells if cell.row_index == i], key=lambda cell: cell.column_index)
        for i in range(table.row_count)
    ]
    for row_cells in rows:
        table_html += "<tr>"
        for cell in row_cells:
            tag = "th" if (cell.kind == "columnHeader" or cell.kind == "rowHeader") else "td"
            cell_spans = ""
            #if cell.column_span > 1:
            #    cell_spans += f" colSpan={cell.column_span}"
            #if cell.row_span > 1:
            #    cell_spans += f" rowSpan={cell.row_span}"
            #table_html += f"<{tag}{cell_spans}>{html.escape(cell.content)}</{tag}>"
            table_html += f"<{tag}>{html.escape(cell.content)}</{tag}>"
        table_html += "</tr>"
    table_html += "</table>"
    return table_html

for i,t in enumerate(result_mkd.tables):
    t_dict=t.as_dict()
    temp = {"id":i,
            "section":None,
            "table_html": table_to_html(t), 
            #"role": t_dict.get("role"), 
            "pageNumber_start": t_dict.get("cells")[0].get("boundingRegions")[0].get("pageNumber"), 
            "pageNumber_end": t_dict.get("cells")[-1].get("boundingRegions")[-1].get("pageNumber"), 
            #"offset": t_dict.get("spans")[0].get("offset"), 
            #"length": t_dict.get("spans")[0].get("length")
            } 
    doc_tables.append(temp)

import pandas as pd 
df_doc_tables = pd.DataFrame(doc_tables)

# Merge sections and tables
df_doc_tables.set_index("id",inplace=True)
for i,s in df_doc_sections_merge.iterrows():
    for p in s.elements:
        if "tables" in p:
            try:
                df_doc_tables.loc[int(p.split("/")[-1]),["section"]] = s.section
            except:
                pass    

df_doc_tables

,section,table_html,pageNumber_start,pageNumber_end
id,,,,
0,13,<table><tr><th>Evaluation Criteria</th><th>Wei...,9,9
1,15,<table><tr><td>&lt;INSERT COUNTERPART NAME&gt;...,11,11
2,15,<table><tr><td>THE REGIONAL MUNICIPALITY OF PE...,11,11
3,44,<table><tr><th>Condition #</th><th>Description...,31,31
4,45,<table><tr><th>Timeline =&gt;</th><th>2021</th...,32,32
5,50,<table><tr><th>Timeline =&gt;</th><th>2021</th...,37,37
6,63,<table><tr><th>Submission</th><th>Number of\nS...,47,47
7,63,<table><tr><th>Submission</th><th>Number of Dr...,48,48
8,166,<table><tr><th>Line Item</th><th>Description</...,86,86
9,167,<table><tr><th>Column A: Line Number</th><th>C...,86,86
10,168,<table><tr><th>Line Item</th><th>Description U...,86,86
11,172,<table><tr><th>Line Item</th><th>Description</...,86,86
12,176,<table><tr><th>Please check the box in the col...,87,87

In [636]:
df_doc_sections_merge["merge_content"] = ""

def get_section_merged_content(c):
    result = ""
    try:
        for j, l in enumerate(c.elements):
                if "sections" in l:            
                    result = result + "\n" + (get_section_merged_content(df_doc_sections_merge.iloc[int(l.split("/")[-1])]))
                if "paragraphs" in l:
                    result = result + "\n" + df_doc_paragraphs.loc[int(l.split("/")[-1])].content
                elif "tables" in l:
                    result = result + "\n" + df_doc_tables.loc[int(l.split("/")[-1])].table_html    
    except:
         print(l)
         raise
    return result

for i,c in df_doc_sections_merge.iterrows():    
    if int(c.level)>0:
        df_doc_sections_merge.loc[i,"merge_content"] = get_section_merged_content(c)

df_doc_sections_merge.head(10)

,section,parent,level,elements,offset,length,section_max,_merge,sections,paragraphs,tables,figures,others,merge_content
0,0,NaN,0,"[/sections/1, /sections/2, /sections/19, /sect...",0,216691,216691,right_only,"[1, 2, 19, 33, 86, 96, 97, 161, 164, 165]",[],[],[],[],
1,1,0,1,[/figures/0],0,52,52,both,[],[],[],[0],[],
2,2,0,1,"[/paragraphs/1, /paragraphs/2, /paragraphs/3, ...",55,29900,29955,both,"[3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 16, 17, 18]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[],[],[],\nRegion of Peel working with you\nRequest for...
3,3,2,1,"[/paragraphs/37, /paragraphs/38, /paragraphs/3...",2666,5633,8299,both,[],"[37, 38, 39, 40, 41, 42, 46, 47, 48, 49, 50, 5...",[],[],[],\n1.3 It is recommended that vendors add norep...
4,4,2,2,"[/paragraphs/68, /paragraphs/69, /paragraphs/7...",8302,3457,11759,both,[],"[68, 69, 70, 71, 72, 76, 77, 78, 79, 80, 81, 8...",[],[],[],\n3.10 Bidder Submissions received by the Agen...
5,5,2,2,"[/paragraphs/84, /paragraphs/85, /paragraphs/8...",11762,1725,13487,both,[],"[84, 85, 86, 90, 91]",[],[],[],"\n. If you are an invited company contact, it ..."
6,6,2,2,"[/paragraphs/92, /paragraphs/93]",13490,204,13694,both,[],"[92, 93]",[],[],[],"\ndifficulties for the Agency, and to reject a..."
7,7,2,2,"[/paragraphs/94, /paragraphs/95, /paragraphs/96]",13697,2110,15807,both,[],"[94, 95, 96]",[],[],[],\nQuantities shown in the Document are approxi...
8,8,2,2,"[/paragraphs/97, /paragraphs/98]",15810,323,16133,both,[],"[97, 98]",[],[],[],"\nIn light of the COVID-19 pandemic, the Contr..."
9,9,2,2,"[/paragraphs/99, /paragraphs/100, /sections/10]",16136,2004,18140,both,[10],"[99, 100]",[],[],[],\nEach Bidder Submission will be evaluated in ...

In [503]:
# Add content to df_doc_sections_merge 
#df_doc_sections_merge = pd.merge(df_doc_sections_merge,df_doc_paragraphs,left_on="section",right_on="section",how="outer",indicator=False)
#df_doc_sections_merge = pd.merge(df_doc_sections_merge,df_doc_tables,left_on="section",right_on="section",how="outer",indicator=False)

In [ ]:
# group by section and concatenate content
#df_doc_paragraphs_grouped = df_doc_paragraphs.groupby("section")["content"].apply(lambda x: ' '.join(x)).reset_index()
#df_doc_paragraphs_grouped

In [651]:
df_doc_sections_merge["content_len"] = df_doc_sections_merge["merge_content"].fillna("").apply(lambda x: len(x))

df_doc_sections_merge.sort_values("section",ascending=True)[df_doc_sections_merge.level=="1"].head(20)

,section,parent,level,elements,offset,length,section_max,_merge,sections,paragraphs,tables,figures,others,merge_content,content_len
1,1,0,1,[/figures/0],0,52,52,both,[],[],[],[0],[],,0
2,2,0,1,"[/paragraphs/1, /paragraphs/2, /paragraphs/3, ...",55,29900,29955,both,"[3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 16, 17, 18]","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[],[],[],\nRegion of Peel working with you\nRequest for...,23819
3,3,2,1,"[/paragraphs/37, /paragraphs/38, /paragraphs/3...",2666,5633,8299,both,[],"[37, 38, 39, 40, 41, 42, 46, 47, 48, 49, 50, 5...",[],[],[],\n1.3 It is recommended that vendors add norep...,4586
19,19,0,1,"[/paragraphs/210, /paragraphs/211, /sections/2...",30205,17840,48045,both,"[20, 21, 22, 24, 26, 29, 30, 31, 32]","[210, 211]",[],[],[],\nDocument 2021-111P Regional Municipality of ...,13288
20,20,19,1,"[/paragraphs/212, /paragraphs/213, /paragraphs...",30375,1178,31553,both,[],"[212, 213, 214, 215, 216]",[],[],[],\nThese Supplementary Terms and Conditions are...,907
33,33,0,1,"[/paragraphs/380, /sections/34, /sections/37, ...",48293,87546,135839,both,"[34, 37, 42, 54, 59]",[380],[],[],[],\nDocument 2021-111P Regional Municipality of ...,70121
34,34,33,1,"[/paragraphs/381, /paragraphs/382, /paragraphs...",48316,8948,57264,both,[35],"[381, 382, 383, 384, 385, 386, 387, 388, 389]",[],[],[],\nTerms of Reference\n2.4. Completed I/I Reduc...,7364
86,86,0,1,"[/paragraphs/971, /paragraphs/972, /sections/8...",136056,5674,141730,both,"[87, 88]","[971, 972]",[],[],[],\nDocument 2021-111P Regional Municipality of ...,5174
87,87,86,1,"[/paragraphs/973, /paragraphs/974, /paragraphs...",136218,796,137014,both,[],"[973, 974, 975, 976]",[],[],[],\n- The project manager and head modeller must...,672
96,96,0,1,[/paragraphs/1012],141969,44,142013,both,[],[1012],[],[],[],\nRegional Municipality of Peel-Procurement Di...,127
97,97,0,1,"[/paragraphs/1013, /paragraphs/1014, /paragrap...",142016,64302,206318,both,"[98, 101, 102, 106, 110, 112, 117, 124, 126, 1...","[1013, 1014, 1015, 1016, 1017, 1018, 1019, 102...",[],[],[],\nAppendix 7.1 Standard Terms and Conditions\n...,50573
98,98,97,1,"[/paragraphs/1029, /sections/99, /sections/100]",145125,2967,148092,both,"[99, 100]",[1029],[],[],[],\nDocument 2021-111P Regional Municipality of ...,2589
161,161,0,1,"[/paragraphs/1330, /paragraphs/1331, /paragrap...",206321,700,207021,both,"[162, 163]","[1330, 1331, 1332, 1333]",[],[],[],\nAppendix 7.4 Agreement for Professional Cons...,500
162,162,161,1,"[/paragraphs/1334, /paragraphs/1335]",206610,124,206734,both,[],"[1334, 1335]",[],[],[],\nThe Consultant shall provide the services mo...,210
164,164,0,1,"[/paragraphs/1339, /paragraphs/1340, /paragrap...",207024,85,207109,both,[],"[1339, 1340, 1341]",[],[],[],\nAppendix 7.4 Agreement for Professional Cons...,138
165,165,0,1,"[/paragraphs/1342, /paragraphs/1343, /paragrap...",207112,9579,216691,both,"[166, 167, 168, 169, 170, 171, 175]","[1342, 1343, 1344, 1345, 1346, 1347, 1348, 135...",[],[7],[],\nand\nFEES\n1. The Region shall pay the Consu...,8183
166,166,165,1,"[/paragraphs/1358, /paragraphs/1359, /paragrap...",209141,983,210124,both,[],"[1358, 1359, 1360, 1361]",[8],[],[],"\nIf the line item and/or table is ""NON-MANDAT...",989

In [652]:
df_doc_sections_merge["level"]= df_doc_sections_merge.level.astype(int)
df_doc_sections_merge.describe()

,section,level,offset,length,section_max,content_len
count,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000
mean,88.000000,2.491525,125536.887006,4813.531073,130350.418079,2917.062147
std,51.239633,0.898981,63929.999685,18339.548676,62570.274258,7102.000262
min,0.000000,0.000000,0.000000,44.000000,52.000000,0.000000
25%,44.000000,2.000000,68721.000000,638.000000,83572.000000,500.000000
50%,88.000000,2.000000,137017.000000,1396.000000,141108.000000,1177.000000
75%,132.000000,3.000000,177909.000000,3082.000000,182040.000000,2590.000000
max,176.000000,5.000000,214817.000000,216691.000000,216691.000000,70121.000000

## Test Layout

In [14]:
"""
# import libraries
import os
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeResult
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest


filename = "./in/2021-111P.pdf"
endpoint = os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT")
key = os.getenv("AZURE_FORM_RECOGNIZER_KEY")

# helper functions

def get_words(page, line):
    result = []
    for word in page.words:
        if _in_span(word, line.spans):
            result.append(word)
    return result


def _in_span(word, spans):
    for span in spans:
        if word.span.offset >= span.offset and (
            word.span.offset + word.span.length
        ) <= (span.offset + span.length):
            return True
    return False


def analyze_layout(filename):
    # sample document
    #formUrl = "https://raw.githubusercontent.com/Azure-Samples/cognitive-services-REST-api-samples/master/curl/form-recognizer/sample-layout.pdf"

    document_intelligence_client = DocumentIntelligenceClient(
        endpoint=endpoint, credential=AzureKeyCredential(key)
    )

    with open(filename, "rb") as f:
        poller = document_intelligence_client.begin_analyze_document(
        "prebuilt-layout",
        #AnalyzeDocumentRequest(url_source=filename),
        AnalyzeDocumentRequest(bytes_source=f.read()),        
        #output_content_format=ContentFormat.MARKDOWN,
    )
        
    #poller = document_intelligence_client.begin_analyze_document(
    #    "prebuilt-layout", AnalyzeDocumentRequest(url_source=filename))

    result: AnalyzeResult = poller.result()

    if result.styles and any([style.is_handwritten for style in result.styles]):
        print("Document contains handwritten content")
    else:
        print("Document does not contain handwritten content")

    for page in result.pages:
        print(f"----Analyzing layout from page #{page.page_number}----")
        print(
            f"Page has width: {page.width} and height: {page.height}, measured with unit: {page.unit}"
        )

        if page.lines:
            for line_idx, line in enumerate(page.lines):
                words = get_words(page, line)
                print(
                    f"...Line # {line_idx} has word count {len(words)} and text '{line.content}' "
                    f"within bounding polygon '{line.polygon}'"
                )

                for word in words:
                    print(
                        f"......Word '{word.content}' has a confidence of {word.confidence}"
                    )

        if page.selection_marks:
            for selection_mark in page.selection_marks:
                print(
                    f"Selection mark is '{selection_mark.state}' within bounding polygon "
                    f"'{selection_mark.polygon}' and has a confidence of {selection_mark.confidence}"
                )

    if result.tables:
        for table_idx, table in enumerate(result.tables):
            print(
                f"Table # {table_idx} has {table.row_count} rows and "
                f"{table.column_count} columns"
            )
            if table.bounding_regions:
                for region in table.bounding_regions:
                    print(
                        f"Table # {table_idx} location on page: {region.page_number} is {region.polygon}"
                    )
            for cell in table.cells:
                print(
                    f"...Cell[{cell.row_index}][{cell.column_index}] has text '{cell.content}'"
                )
                if cell.bounding_regions:
                    for region in cell.bounding_regions:
                        print(
                            f"...content on page {region.page_number} is within bounding polygon '{region.polygon}'"
                        )

    print("----------------------------------------")


analyze_layout(filename)
"""

Document contains handwritten content
----Analyzing layout from page #1----
Page has width: 8.5 and height: 11, measured with unit: LengthUnit.INCH
...Line # 0 has word count 1 and text 'Region' within bounding polygon '[1.2105, 0.5863, 2.1126, 0.5859, 2.1127, 0.867, 1.2107, 0.8674]'
......Word 'Region' has a confidence of 0.995
...Line # 1 has word count 2 and text 'of Peel' within bounding polygon '[1.2122, 0.8878, 2.1172, 0.8843, 2.1181, 1.1167, 1.2131, 1.1202]'
......Word 'of' has a confidence of 0.998
......Word 'Peel' has a confidence of 0.992
...Line # 2 has word count 3 and text 'working with you' within bounding polygon '[0.7826, 1.1303, 2.1139, 1.1325, 2.1135, 1.3311, 0.7823, 1.3289]'
......Word 'working' has a confidence of 0.998
......Word 'with' has a confidence of 0.989
......Word 'you' has a confidence of 0.998
...Line # 3 has word count 3 and text 'Request for Proposal' within bounding polygon '[3.2083, 1.3309, 5.3314, 1.3288, 5.3317, 1.5662, 3.2085, 1.5683]'
......Word 'Request' has a confidence of 0.998
......Word 'for' has a confidence of 0.995
......Word 'Proposal' has a confidence of 0.995
...Line # 4 has word count 3 and text 'Document Number: 2021-111P' within bounding polygon '[0.5513, 1.9167, 2.8016, 1.9105, 2.8021, 2.0792, 0.5518, 2.0855]'
......Word 'Document' has a confidence of 0.995
......Word 'Number:' has a confidence of 0.993
......Word '2021-111P' has a confidence of 0.994
...Line # 5 has word count 2 and text 'Document Title:' within bounding polygon '[0.55, 2.266, 1.7206, 2.2654, 1.7207, 2.4292, 0.55, 2.4298]'
......Word 'Document' has a confidence of 0.995
......Word 'Title:' has a confidence of 0.995
...Line # 6 has word count 12 and text 'BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1 WITHIN THE CITY OF' within bounding polygon '[2.0397, 2.2571, 7.5471, 2.2538, 7.5472, 2.4292, 2.0399, 2.4325]'
......Word 'BLOCK' has a confidence of 0.997
......Word 'STUDY' has a confidence of 0.993
......Word 'AND' has a confidence of 0.999
......Word 'PRELIMINARY' has a confidence of 0.993
......Word 'DESIGN' has a confidence of 0.996
......Word '-' has a confidence of 0.995
......Word 'BLOCK' has a confidence of 0.998
......Word '1' has a confidence of 0.995
......Word 'WITHIN' has a confidence of 0.998
......Word 'THE' has a confidence of 0.999
......Word 'CITY' has a confidence of 0.992
......Word 'OF' has a confidence of 0.999
...Line # 7 has word count 1 and text 'MISSISSAUGA' within bounding polygon '[2.0398, 2.4413, 3.1079, 2.4415, 3.1079, 2.6017, 2.0397, 2.6015]'
......Word 'MISSISSAUGA' has a confidence of 0.993
...Line # 8 has word count 2 and text 'Date Issued:' within bounding polygon '[0.5503, 2.7971, 1.4719, 2.7993, 1.4716, 2.9608, 0.5499, 2.9586]'
......Word 'Date' has a confidence of 0.992
......Word 'Issued:' has a confidence of 0.956
...Line # 9 has word count 4 and text 'Monday, February 22, 2021' within bounding polygon '[2.04, 2.7943, 3.9501, 2.7921, 3.9503, 2.9745, 2.0402, 2.9766]'
......Word 'Monday,' has a confidence of 0.993
......Word 'February' has a confidence of 0.993
......Word '22,' has a confidence of 0.992
......Word '2021' has a confidence of 0.99
...Line # 10 has word count 14 and text 'ELECTRONIC BID SUBMISSIONS ONLY shall be received by the Agency through the Bidding System' within bounding polygon '[0.5487, 3.1278, 7.8981, 3.1405, 7.8978, 3.3373, 0.5484, 3.324]'
......Word 'ELECTRONIC' has a confidence of 0.993
......Word 'BID' has a confidence of 0.995
......Word 'SUBMISSIONS' has a confidence of 0.993
......Word 'ONLY' has a confidence of 0.992
......Word 'shall' has a confidence of 0.996
......Word 'be' has a confidence of 0.997
......Word 'received' has a confidence of 0.994
......Word 'by' has a confidence of 0.992
......Word 'the' has a confidence of 0.999
......Word 'Agency' has a confidence of 0.997
......Word 'through' has a confidence of 0.999
......Word 'the' has a confidence of 0.999
......Word 'Bidding' has a confidence of 0.997
......Word 'System' has a confidence of 0.992
...Line # 11 has word count 3 and text 'no later than:' within bounding polygon '[0.5506, 3.3319, 1.5327, 3.3324, 1.5327, 3.4859, 0.5505, 3.4854]'
......Word 'no' has a confidence of 0.995
......Word 'later' has a confidence of 0.996
......Word 'than:' has a confidence of 0.996
...Line # 12 has word count 4 and text '12:00 noon local time' within bounding polygon '[3.3089, 3.6799, 5.2938, 3.6833, 5.2935, 3.8807, 3.3085, 3.8773]'
......Word '12:00' has a confidence of 0.996
......Word 'noon' has a confidence of 0.992
......Word 'local' has a confidence of 0.996
......Word 'time' has a confidence of 0.992
...Line # 13 has word count 4 and text 'Wednesday, March 17, 2021' within bounding polygon '[3.0015, 3.9039, 5.5778, 3.9024, 5.5779, 4.1213, 3.0017, 4.1228]'
......Word 'Wednesday,' has a confidence of 0.994
......Word 'March' has a confidence of 0.997
......Word '17,' has a confidence of 0.993
......Word '2021' has a confidence of 0.99
...Line # 14 has word count 9 and text 'It is the Bidder's sole responsibility to ensure that:' within bounding polygon '[0.5479, 4.2913, 4.2383, 4.2968, 4.2381, 4.4779, 0.5476, 4.4724]'
......Word 'It' has a confidence of 0.962
......Word 'is' has a confidence of 0.995
......Word 'the' has a confidence of 0.999
......Word 'Bidder's' has a confidence of 0.98
......Word 'sole' has a confidence of 0.986
......Word 'responsibility' has a confidence of 0.993
......Word 'to' has a confidence of 0.999
......Word 'ensure' has a confidence of 0.995
......Word 'that:' has a confidence of 0.992
...Line # 15 has word count 15 and text '. the submission is received electronically by the Agency through the Bidding System by the' within bounding polygon '[0.8111, 4.5267, 7.7137, 4.5217, 7.7138, 4.7065, 0.8113, 4.7111]'
......Word '.' has a confidence of 0.59
......Word 'the' has a confidence of 0.999
......Word 'submission' has a confidence of 0.993
......Word 'is' has a confidence of 0.997
......Word 'received' has a confidence of 0.994
......Word 'electronically' has a confidence of 0.993
......Word 'by' has a confidence of 0.998
......Word 'the' has a confidence of 0.999
......Word 'Agency' has a confidence of 0.997
......Word 'through' has a confidence of 0.997
......Word 'the' has a confidence of 0.998
......Word 'Bidding' has a confidence of 0.997
......Word 'System' has a confidence of 0.998
......Word 'by' has a confidence of 0.999
......Word 'the' has a confidence of 0.999
...Line # 16 has word count 5 and text 'date and time specified above' within bounding polygon '[1.0491, 4.706, 3.2421, 4.7056, 3.2422, 4.8738, 1.0491, 4.8742]'
......Word 'date' has a confidence of 0.992
......Word 'and' has a confidence of 0.998
......Word 'time' has a confidence of 0.992
......Word 'specified' has a confidence of 0.994
......Word 'above' has a confidence of 0.995
...Line # 17 has word count 9 and text '. the submission is accompanied by all required documentation' within bounding polygon '[0.8159, 4.9345, 5.6053, 4.927, 5.6056, 5.1011, 0.8162, 5.1097]'
......Word '.' has a confidence of 0.606
......Word 'the' has a confidence of 0.999
......Word 'submission' has a confidence of 0.994
......Word 'is' has a confidence of 0.998
......Word 'accompanied' has a confidence of 0.992
......Word 'by' has a confidence of 0.998
......Word 'all' has a confidence of 0.997
......Word 'required' has a confidence of 0.995
......Word 'documentation' has a confidence of 0.993
...Line # 18 has word count 6 and text 'Procurement Representative: Amanda Tanti, Procurement Analyst' within bounding polygon '[0.4736, 5.2839, 5.309, 5.2859, 5.309, 5.4655, 0.4735, 5.4635]'
......Word 'Procurement' has a confidence of 0.992
......Word 'Representative:' has a confidence of 0.992
......Word 'Amanda' has a confidence of 0.995
......Word 'Tanti,' has a confidence of 0.994
......Word 'Procurement' has a confidence of 0.994
......Word 'Analyst' has a confidence of 0.994
...Line # 19 has word count 6 and text 'Telephone Number: (905) 791-7800, ext. 4165' within bounding polygon '[0.4704, 5.457, 3.751, 5.4565, 3.751, 5.6377, 0.4704, 5.6382]'
......Word 'Telephone' has a confidence of 0.993
......Word 'Number:' has a confidence of 0.995
......Word '(905)' has a confidence of 0.994
......Word '791-7800,' has a confidence of 0.992
......Word 'ext.' has a confidence of 0.995
......Word '4165' has a confidence of 0.991
----Analyzing layout from page #2----
Page has width: 8.5 and height: 11, measured with unit: LengthUnit.INCH
...Line # 0 has word count 2 and text 'Document 2021-111P' within bounding polygon '[1.2392, 0.4924, 2.7916, 0.4888, 2.7919, 0.6542, 1.2396, 0.6578]'
......Word 'Document' has a confidence of 0.995
......Word '2021-111P' has a confidence of 0.993
...Line # 1 has word count 5 and text 'Regional Municipality of Peel-Procurement Division' within bounding polygon '[3.4904, 0.4902, 7.2561, 0.4908, 7.256, 0.6736, 3.4904, 0.673]'
......Word 'Regional' has a confidence of 0.989
......Word 'Municipality' has a confidence of 0.992
......Word 'of' has a confidence of 0.998
......Word 'Peel-Procurement' has a confidence of 0.992
......Word 'Division' has a confidence of 0.995
...Line # 2 has word count 11 and text 'BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1WITHIN THE CITY OF' within bounding polygon '[1.2404, 0.665, 6.8364, 0.6661, 6.8363, 0.8366, 1.2404, 0.8355]'
......Word 'BLOCK' has a confidence of 0.998
......Word 'STUDY' has a confidence of 0.998
......Word 'AND' has a confidence of 0.996
......Word 'PRELIMINARY' has a confidence of 0.995
......Word 'DESIGN' has a confidence of 0.995
......Word '-' has a confidence of 0.995
......Word 'BLOCK' has a confidence of 0.998
......Word '1WITHIN' has a confidence of 0.996
......Word 'THE' has a confidence of 0.997
......Word 'CITY' has a confidence of 0.992
......Word 'OF' has a confidence of 0.993
...Line # 3 has word count 1 and text 'MISSISSAUGA' within bounding polygon '[1.237, 0.8489, 2.3259, 0.8483, 2.3259, 1.0078, 1.2371, 1.0084]'
......Word 'MISSISSAUGA' has a confidence of 0.994
...Line # 4 has word count 1 and text 'Index' within bounding polygon '[1.233, 1.2034, 1.6584, 1.2055, 1.6576, 1.3537, 1.2323, 1.3516]'
......Word 'Index' has a confidence of 0.992
...Line # 5 has word count 13 and text 'For BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1 WITHIN THE CITY OF' within bounding polygon '[1.2389, 1.5609, 7.0106, 1.5611, 7.0106, 1.7399, 1.2389, 1.7397]'
......Word 'For' has a confidence of 0.998
......Word 'BLOCK' has a confidence of 0.992
......Word 'STUDY' has a confidence of 0.993
......Word 'AND' has a confidence of 0.995
......Word 'PRELIMINARY' has a confidence of 0.993
......Word 'DESIGN' has a confidence of 0.995
......Word '-' has a confidence of 0.995
......Word 'BLOCK' has a confidence of 0.998
......Word '1' has a confidence of 0.992
......Word 'WITHIN' has a confidence of 0.997
......Word 'THE' has a confidence of 0.999
......Word 'CITY' has a confidence of 0.989
......Word 'OF' has a confidence of 0.999
...Line # 6 has word count 9 and text 'MISSISSAUGA, as required, and as specified within this Document.' within bounding polygon '[1.2363, 1.739, 5.7213, 1.7431, 5.7212, 1.9261, 1.2362, 1.9221]'
......Word 'MISSISSAUGA,' has a confidence of 0.993
......Word 'as' has a confidence of 0.996
......Word 'required,' has a confidence of 0.992
......Word 'and' has a confidence of 0.997
......Word 'as' has a confidence of 0.997
......Word 'specified' has a confidence of 0.992
......Word 'within' has a confidence of 0.996
......Word 'this' has a confidence of 0.992
......Word 'Document.' has a confidence of 0.994
...Line # 7 has word count 1 and text '1.' within bounding polygon '[1.2556, 2.1106, 1.365, 2.1105, 1.3652, 2.253, 1.2558, 2.2531]'
......Word '1.' has a confidence of 0.989
...Line # 8 has word count 2 and text 'Cover Sheet' within bounding polygon '[1.737, 2.1007, 2.5904, 2.1001, 2.5905, 2.2622, 1.7371, 2.2628]'
......Word 'Cover' has a confidence of 0.998
......Word 'Sheet' has a confidence of 0.996
...Line # 9 has word count 2 and text '2. Index' within bounding polygon '[1.23, 2.4531, 2.1331, 2.4529, 2.1331, 2.6086, 1.2301, 2.6088]'
......Word '2.' has a confidence of 0.994
......Word 'Index' has a confidence of 0.987
...Line # 10 has word count 1 and text '3.' within bounding polygon '[1.2396, 2.8093, 1.3664, 2.809, 1.3666, 2.9588, 1.2399, 2.959]'
......Word '3.' has a confidence of 0.994
...Line # 11 has word count 4 and text 'Instructions to Bidders (ITB)' within bounding polygon '[1.7344, 2.7957, 3.591, 2.7959, 3.5904, 2.9865, 1.7337, 2.9804]'
......Word 'Instructions' has a confidence of 0.989
......Word 'to' has a confidence of 0.997
......Word 'Bidders' has a confidence of 0.994
......Word '(ITB)' has a confidence of 0.984
...Line # 12 has word count 1 and text '4.' within bounding polygon '[1.2383, 3.1582, 1.3666, 3.1581, 1.3666, 3.3036, 1.2384, 3.3036]'
......Word '4.' has a confidence of 0.992
...Line # 13 has word count 4 and text 'Supplementary Terms and Conditions' within bounding polygon '[1.7331, 3.1516, 4.2517, 3.1449, 4.2522, 3.329, 1.7336, 3.3357]'
......Word 'Supplementary' has a confidence of 0.993
......Word 'Terms' has a confidence of 0.992
......Word 'and' has a confidence of 0.994
......Word 'Conditions' has a confidence of 0.992
...Line # 14 has word count 1 and text '5.' within bounding polygon '[1.2427, 3.5105, 1.3692, 3.5103, 1.3694, 3.6639, 1.2429, 3.6641]'
......Word '5.' has a confidence of 0.992
...Line # 15 has word count 4 and text 'Terms of Reference (TOR)' within bounding polygon '[1.7341, 3.4932, 3.5255, 3.4962, 3.5246, 3.6899, 1.7332, 3.6816]'
......Word 'Terms' has a confidence of 0.992
......Word 'of' has a confidence of 0.995
......Word 'Reference' has a confidence of 0.994
......Word '(TOR)' has a confidence of 0.977
...Line # 16 has word count 1 and text '6.' within bounding polygon '[1.2418, 3.8611, 1.3667, 3.8609, 1.3669, 4.0124, 1.242, 4.0126]'
......Word '6.' has a confidence of 0.992
...Line # 17 has word count 8 and text 'Request for Information (RFI) - Bidder Submission Requirements' within bounding polygon '[1.7342, 3.8481, 6.0529, 3.8454, 6.053, 4.0354, 1.7343, 4.0382]'
......Word 'Request' has a confidence of 0.992
......Word 'for' has a confidence of 0.996
......Word 'Information' has a confidence of 0.975
......Word '(RFI)' has a confidence of 0.914
......Word '-' has a confidence of 0.995
......Word 'Bidder' has a confidence of 0.994
......Word 'Submission' has a confidence of 0.993
......Word 'Requirements' has a confidence of 0.992
...Line # 18 has word count 1 and text '7.' within bounding polygon '[1.2413, 4.207, 1.3671, 4.2069, 1.3672, 4.3596, 1.2415, 4.3598]'
......Word '7.' has a confidence of 0.989
...Line # 19 has word count 1 and text 'Appendices:' within bounding polygon '[1.7353, 4.2049, 2.5689, 4.2078, 2.5683, 4.3818, 1.7347, 4.3789]'
......Word 'Appendices:' has a confidence of 0.992
...Line # 20 has word count 1 and text '7.1' within bounding polygon '[1.7418, 4.3865, 1.9485, 4.3863, 1.9487, 4.5349, 1.742, 4.5351]'
......Word '7.1' has a confidence of 0.998
...Line # 21 has word count 4 and text 'Standard Terms and Conditions' within bounding polygon '[2.2394, 4.377, 4.3547, 4.381, 4.3544, 4.5531, 2.2391, 4.5492]'
......Word 'Standard' has a confidence of 0.995
......Word 'Terms' has a confidence of 0.995
......Word 'and' has a confidence of 0.998
......Word 'Conditions' has a confidence of 0.995
...Line # 22 has word count 1 and text '7.2' within bounding polygon '[1.7415, 4.5593, 1.9647, 4.5595, 1.9646, 4.7134, 1.7414, 4.7132]'
......Word '7.2' has a confidence of 0.996
...Line # 23 has word count 9 and text 'Public Works Linear CAD Submission Requirements, Capital Works, June' within bounding polygon '[2.2371, 4.5506, 7.1178, 4.5512, 7.1177, 4.738, 2.237, 4.7372]'
......Word 'Public' has a confidence of 0.992
......Word 'Works' has a confidence of 0.995
......Word 'Linear' has a confidence of 0.993
......Word 'CAD' has a confidence of 0.997
......Word 'Submission' has a confidence of 0.993
......Word 'Requirements,' has a confidence of 0.992
......Word 'Capital' has a confidence of 0.994
......Word 'Works,' has a confidence of 0.993
......Word 'June' has a confidence of 0.989
...Line # 24 has word count 1 and text '2015' within bounding polygon '[2.2403, 4.7394, 2.5906, 4.7394, 2.5906, 4.8924, 2.2402, 4.8924]'
......Word '2015' has a confidence of 0.991
...Line # 25 has word count 1 and text '7.3' within bounding polygon '[1.7426, 4.9076, 1.9599, 4.9077, 1.9598, 5.0634, 1.7425, 5.0633]'
......Word '7.3' has a confidence of 0.999
...Line # 26 has word count 2 and text 'Supporting Material' within bounding polygon '[2.2359, 4.9063, 3.5441, 4.9043, 3.5443, 5.0836, 2.2362, 5.0856]'
......Word 'Supporting' has a confidence of 0.995
......Word 'Material' has a confidence of 0.993
...Line # 27 has word count 1 and text '7.4' within bounding polygon '[1.7419, 5.0872, 1.9595, 5.0873, 1.9594, 5.2407, 1.7418, 5.2406]'
......Word '7.4' has a confidence of 0.995
...Line # 28 has word count 5 and text 'Agreement for Professional Consulting Services' within bounding polygon '[2.2321, 5.0833, 5.4054, 5.0812, 5.4055, 5.263, 2.2322, 5.2647]'
......Word 'Agreement' has a confidence of 0.995
......Word 'for' has a confidence of 0.999
......Word 'Professional' has a confidence of 0.993
......Word 'Consulting' has a confidence of 0.994
......Word 'Services' has a confidence of 0.995
...Line # 29 has word count 1 and text '7.5' within bounding polygon '[1.7423, 5.2633, 1.9624, 5.2644, 1.9616, 5.4183, 1.7415, 5.4171]'
......Word '7.5' has a confidence of 0.996
...Line # 30 has word count 4 and text 'Online Bidding System forms' within bounding polygon '[2.2375, 5.2557, 4.172, 5.2591, 4.1717, 5.44, 2.2372, 5.4366]'
......Word 'Online' has a confidence of 0.997
......Word 'Bidding' has a confidence of 0.996
......Word 'System' has a confidence of 0.998
......Word 'forms' has a confidence of 0.998
...Line # 31 has word count 1 and text 'V-20190321' within bounding polygon '[1.2347, 10.3552, 1.9965, 10.3577, 1.9961, 10.4967, 1.2343, 10.4943]'
......Word 'V-20190321' has a confidence of 0.995
...Line # 32 has word count 1 and text '1' within bounding polygon '[4.2138, 10.3444, 4.2783, 10.3448, 4.2775, 10.4704, 4.2131, 10.47]'
......Word '1' has a confidence of 0.997
----Analyzing layout from page #3----
Page has width: 8.5 and height: 11, measured with unit: LengthUnit.INCH
...Line # 0 has word count 2 and text 'Document 2021-111P' within bounding polygon '[1.2381, 0.4918, 2.7902, 0.4884, 2.7906, 0.6529, 1.2385, 0.6563]'
......Word 'Document' has a confidence of 0.995
......Word '2021-111P' has a confidence of 0.993
...Line # 1 has word count 5 and text 'Regional Municipality of Peel-Procurement Division' within bounding polygon '[3.4912, 0.4891, 7.2547, 0.4891, 7.2547, 0.6719, 3.4912, 0.6719]'
......Word 'Regional' has a confidence of 0.992
......Word 'Municipality' has a confidence of 0.992
......Word 'of' has a confidence of 0.998
......Word 'Peel-Procurement' has a confidence of 0.989
......Word 'Division' has a confidence of 0.993
...Line # 2 has word count 12 and text 'BLOCK STUDY AND PRELIMINARY DESIGN - BLOCK 1 WITHIN THE CITY OF' within bounding polygon '[1.2402, 0.6644, 6.8758, 0.6645, 6.8758, 0.8348, 1.2402, 0.8347]'
......Word 'BLOCK' has a confidence of 0.998
......Word 'STUDY' has a confidence of 0.999
......Word 'AND' has a confidence of 0.997
......Word 'PRELIMINARY' has a confidence of 0.995
......Word 'DESIGN' has a confidence of 0.994
......Word '-' has a confidence of 0.996
......Word 'BLOCK' has a confidence of 0.998
......Word '1' has a confidence of 0.992
......Word 'WITHIN' has a confidence of 0.995
......Word 'THE' has a confidence of 0.998
......Word 'CITY' has a confidence of 0.992
......Word 'OF' has a confidence of 0.999